---
- name: Deploy the redirects
  hosts: web
  roles:
    - role: practical-ansible.nginx_redirect
      project_name: global-zak-pavel-redirects
      server_names: pavelzak.cz,www.pavelzak.cz,www.pavel.zak.global
      destination_domain: pavel.zak.global
      admin_email: pavel@zak.global
      become: true

- name: Deploy the personal site
  hosts: web
  roles:
    - role: practical-ansible.nginx_static
      project_name: global-zak-pavel
      server_names: pavel.zak.global
      project_environment: production
      admin_email: pavel@zak.global
      dir_source: src/
      become: true

- name: Deploy the root site
  hosts: web
  roles:
    - role: practical-ansible.nginx_static
      project_name: global-zak
      server_names: zak.global
      project_environment: production
      admin_email: pavel@zak.global
      dir_source: root/
      become: true
