name: Continuous deployment
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-node-${{ hashFiles('**requirements**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy install -r requirements-ansible.yml
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.PRODUCTION_KNOWN_HOSTS }}
      - name: Deploy to Production
        env:
          DEPLOY_HOST: ${{ secrets.PRODUCTION_DEPLOY_HOST }}
        run: |
          echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
          echo -e "[web]\n$DEPLOY_HOST" > inventory.yml
          ansible-playbook deploy.yml -i inventory.yml
