name: Continuous integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-node-${{ hashFiles('**requirements**') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          ansible-galaxy install -r requirements-ansible.yml -p ./roles
